In [1]:
import numpy as np
import scipy.signal as signal

In [13]:
def RD_realtocomp(s):
    Nf  = s.size
    # if Nf is a multiple of 2, fftshift(fftshift(X)) = X
    if ( Nf % 2 ) != 0 :
        error( "Nf should be a multiple of 2" )

    h = np.zeros(Nf)
    h[ 0 ] = 1
    h[ int( Nf / 2) ] = 1
    h[ 1 : int(Nf / 2) ] = 2

    RDs = np.fft.ifft(np.fft.fftshift(s))
    RDh = RDs * h
    RDc = np.fft.fftshift(np.fft.fft(RDh))

    return RDc[::2]

def RD_realtocomp_np(s):
    Nf  = s.size
    # if Nf is a multiple of 2, fftshift(fftshift(X)) = X
    if ( Nf % 2 ) != 0 :
        error( "Nf should be a multiple of 2" )
    return np.conjugate(signal.hilbert(s))[::2]

In [14]:
a = np.random.rand(10)

In [15]:
a

array([0.39353922, 0.92060895, 0.11902563, 0.74503356, 0.60450705,
       0.82452613, 0.13037045, 0.18256018, 0.66541074, 0.3043163 ])

In [16]:
RD_realtocomp(a)

array([0.39353922+0.46108291j, 0.11902563-0.03248219j,
       0.60450705-0.05831417j, 0.13037045-0.45919357j,
       0.66541074+0.08890701j])

In [17]:
RD_realtocomp_np(a)

array([0.39353922+0.46108291j, 0.11902563-0.03248219j,
       0.60450705-0.05831417j, 0.13037045-0.45919357j,
       0.66541074+0.08890701j])